export const SkillData = [
  { name: "HTML 5",          Image: "/html.png",       width: 80, height: 80 },
  { name: "CSS",             Image: "/css.png",        width: 80, height: 80 },
  { name: "JavaScript",      Image: "/js.png",         width: 65, height: 65 },
  { name: "TypeScript",      Image: "/ts.png",         width: 80, height: 80 },
  { name: "React",           Image: "/react.png",      width: 80, height: 80 },
  { name: "Next.js 14",      Image: "/next.png",       width: 80, height: 80 },
  { name: "Node.js",         Image: "/node-js.png",    width: 80, height: 80 },
  { name: "Express",         Image: "/express.png",    width: 90, height: 90 },
  { name: "MongoDB",         Image: "/mongodb.png",    width: 40, height: 40 },
  { name: "Prisma",          Image: "/prisma.png",     width: 80, height: 80 },
  { name: "Tailwind CSS",    Image: "/tailwind.png",   width: 80, height: 80 },
  { name: "Rust",            Image: "/Rust.png",       width: 90, height: 90 },
  { name: "C++",             Image: "/C++.png",        width: 90, height: 90 },
  { name: "Stripe",          Image: "/stripe.png",     width: 80, height: 80 },
  { name: "Unreal Engine 5", Image: "/ue5.png",     width: 80, height: 80 },
  { name: "Blueprint",       Image: "/BP.png",  width: 80, height: 80 },
]

export const Quotes = [
  { quote: "The only true wisdom is in knowing you know nothing.",             author: "Socrates"          },
  { quote: "I think, therefore I am.",                                         author: "René Descartes"    },
  { quote: "We are what we repeatedly do. Excellence, then, is not an act, but a habit.", author: "Aristotle" },
  { quote: "Life must be understood backward. But it must be lived forward.",  author: "Søren Kierkegaard" },
  { quote: "He who is not courageous enough to take risks will accomplish nothing in life.", author: "Muhammad Ali" },
  { quote: "The unexamined life is not worth living.",                         author: "Socrates"          },
  { quote: "I have not failed. I've just found 10,000 ways that won't work.", author: "Thomas Edison"     },
  { quote: "Happiness depends upon ourselves.",                                author: "Aristotle"         },
  { quote: "The only way to do great work is to love what you do.",           author: "Steve Jobs"        },
  { quote: "The only source of knowledge is experience.",                      author: "Albert Einstein"   },
]